server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/fraude
          jwk-set-uri: http://localhost:8084/realms/fraude/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: alert-service
          uri: http://alert-service:8082
          predicates:
            - Path=/api/alerts/**
          filters:
            - RewritePath=/api/alerts/?(?<segment>.*), /alerts/${segment}
        - id: ingestion-service
          uri: http://ingestion-service:8083
          predicates:
            - Path=/api/ingest/**
          filters:
            - RewritePath=/api/ingest/(?<segment>.*), /ingest/${segment}
